# Generated by Django 4.1.4 on 2023-04-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genshinwishoracle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimogemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrimogemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('associated_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genshinwishoracle.primogemrecord')),
            ],
        ),
    ]
