# Generated by Django 4.1.4 on 2023-04-08 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genshinwishoracle', '0003_remove_primogemsnapshot_associated_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimogemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numprimos', models.IntegerField(default=0)),
                ('numgenesis', models.IntegerField(default=0)),
                ('numfates', models.IntegerField(default=0)),
                ('numstarglitter', models.IntegerField(default=0)),
                ('character_pity', models.IntegerField(default=0)),
                ('character_guaranteed', models.BooleanField(default=False)),
                ('weapon_pity', models.IntegerField(default=0)),
                ('weapon_guaranteed', models.BooleanField(default=False)),
                ('weapon_fate_points', models.IntegerField(default=0)),
                ('welkin_user', models.BooleanField(default=False)),
                ('battlepass_user', models.BooleanField(default=False)),
                ('banners', models.ManyToManyField(to='genshinwishoracle.banner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrimogemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('primogem_value', models.IntegerField()),
                ('associated_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.primogemrecord')),
            ],
        ),
    ]
