# Generated by Django 4.1.4 on 2023-02-23 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numprimos', models.IntegerField(default=0)),
                ('numgenesis', models.IntegerField(default=0)),
                ('numfates', models.IntegerField(default=0)),
                ('numstarglitter', models.IntegerField(default=0)),
                ('character_pity', models.IntegerField(default=0)),
                ('character_guaranteed', models.BooleanField(default=False)),
                ('weapon_pity', models.IntegerField(default=0)),
                ('weapon_guaranteed', models.BooleanField(default=False)),
                ('weapon_fate_points', models.IntegerField(default=0)),
                ('welkin_user', models.BooleanField(default=False)),
                ('battlepass_user', models.BooleanField(default=False)),
                ('banners', models.ManyToManyField(to='analyze.banner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
