# Generated by Django 4.1.4 on 2023-01-25 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyze', '0002_auto_20230124_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numprimos', models.IntegerField()),
                ('numgenesis', models.IntegerField()),
                ('numfates', models.IntegerField()),
                ('numstarglitter', models.IntegerField()),
                ('character_pity', models.IntegerField()),
                ('character_guaranteed', models.BooleanField()),
                ('character_fate_points', models.IntegerField()),
                ('weapon_pity', models.IntegerField()),
                ('weapon_guaranteed', models.BooleanField()),
                ('weapon_fate_points', models.IntegerField()),
                ('welkin_user', models.BooleanField()),
                ('battlepass_user', models.BooleanField()),
                ('banners', models.ManyToManyField(to='analyze.banner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
