# Generated by Django 4.1.4 on 2023-04-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_primogem_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primogem_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.primogemrecord'),
        ),
    ]
