# Generated by Django 4.1.4 on 2022-12-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('limited', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('limited', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rateup_five_stars', models.ManyToManyField(to='analyze.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rateup_five_star', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyze.character')),
            ],
        ),
    ]
