# Generated by Django 4.1.4 on 2023-01-24 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('limited', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('limited', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponBanner',
            fields=[
                ('banner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analyze.banner')),
                ('name', models.CharField(max_length=64)),
                ('enddate', models.DateField()),
                ('rateups', models.ManyToManyField(to='analyze.weapon')),
            ],
            bases=('analyze.banner',),
        ),
        migrations.CreateModel(
            name='CharacterBanner',
            fields=[
                ('banner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analyze.banner')),
                ('name', models.CharField(max_length=64)),
                ('enddate', models.DateField()),
                ('rateups', models.ManyToManyField(to='analyze.character')),
            ],
            bases=('analyze.banner',),
        ),
    ]
