# Generated by Django 4.1.4 on 2023-01-06 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weaponbanner',
            old_name='rateup_five_stars',
            new_name='rateups',
        ),
        migrations.RemoveField(
            model_name='characterbanner',
            name='rateup_five_star',
        ),
        migrations.AddField(
            model_name='characterbanner',
            name='rateups',
            field=models.ManyToManyField(to='analyze.character'),
        ),
    ]
