# Generated by Django 4.1.4 on 2023-03-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_alter_banner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-rarity', 'name']},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['-rarity', 'name']},
        ),
        migrations.AlterField(
            model_name='weaponbanner',
            name='rateups',
            field=models.ManyToManyField(blank=True, to='analyze.weapon'),
        ),
    ]
